name: Splatgames
version: '${project.version}'
main: fr.ernicani.Splatgames
api-version: 1.18
author: ErNicani
description: Splatgames plugin
commands:
  start:
    description: Start a game
    usage: /start
    permission: splatgames.start
    permission-message: You don't have permission to start a game
  setlobby:
    description: Set the lobby
    usage: /setlobby
    permission: splatgames.setlobby
    permission-message: You don't have permission to set the lobby

